name: Deploy to EC2

on:
  push:
    branches: [ master ]

env:
  DOCKER_COMPOSE_VERSION: 1.29.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/ubuntu/app"

      - name: Install Docker Compose and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create volume directory with proper permissions
            sudo mkdir -p /opt/medium-plan/postgres-data
            sudo chown -R 1000:1000 /opt/medium-plan/postgres-data
            sudo chmod -R 755 /opt/medium-plan
            ls -la frontend/ backend/
            # Set proper permissions (read-only for owner)
            sudo chmod -R 400 frontend/.env
            sudo chmod -R 400 backend/.env
            cd /home/ubuntu/app
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d --build
